### ISSUE TITLE
Min Max macros in Windows (again)

### ISSUE THREAD

**Issue by sphaero** [gallickgunner/ImGui-Addons#43]
Not sure what change made this happen but I can't build on Windows anymore with imgui 1.85.

```
C:\projects\gazebosc-sphaero\ext\ImGui-Addons\FileBrowser\ImGuiFileBrowser.cpp(121,46): error C2589: '(': illegal token on right side of '::' [C:\projects\gazebosc-sphaero\build\gazebosc.vcxproj]
C:\projects\gazebosc-sphaero\ext\ImGui-Addons\FileBrowser\ImGuiFileBrowser.cpp(121): error C2144: syntax error: 'unknown-type' should be preceded by ')' [C:\projects\gazebosc-sphaero\build\gazebosc.vcxproj]
```
Very much related to #7 

I think it can also be fixed by using `std::max<float>` instead of `std::max` etc

However it's just a workaround.

**Comment by sphaero** [comment]
I fixed it by adding a NOMINMAX definition to the compiler (-DNOMINMAX). Seems this happens a lot on windows?

**Comment by gallickgunner** [comment]
> I fixed it by adding a NOMINMAX definition to the compiler (-DNOMINMAX). Seems this happens a lot on windows?

Don't really understand why you had to define it in compiler since I've already defined in the file. Yeah this happens on windows just because stupid Microsoft had to define the macros in `windef.h`. The solution is to define the macro as I've done but it seems to be failing, dunno why. The other solutions are as you said to explicitly define the type using `<float>`, wrap the function in paranthesis, or avoid using `std::min/max` altogether.

**Comment by sphaero** [comment]
I don't either. But it works for me. I didn't want to dive into what windows includes are messing this up since I don't work on Windows :confused:
